name: web_directory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^7.0.1
  flutter_native_splash: ^2.4.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^14.1.4
  latlong2: ^0.9.1
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/.env
    - assets/images/default_pp.png
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icone/favicon.ico"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icone/favicon.ico"
    background_color: "##242422"
    theme_color: "##FFFFFF"


flutter_native_splash:
  color: "##242422"
  image: "assets/images/icone/favicon.ico"
  android: true
  ios: true
  web: true